// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sondage_Project.Data;

namespace Sondage_Project.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211230145049_UpdateSondageCheck")]
    partial class UpdateSondageCheck
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sondage_Project.Data.Models.Sondage", b =>
                {
                    b.Property<int>("SondageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer_1")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer_2")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer_3")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Answer_4")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Counter_1")
                        .HasColumnType("int");

                    b.Property<int>("Counter_2")
                        .HasColumnType("int");

                    b.Property<int>("Counter_3")
                        .HasColumnType("int");

                    b.Property<int>("Counter_4")
                        .HasColumnType("int");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<bool>("MultipleAnswer")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("answer1check")
                        .HasColumnType("bit");

                    b.Property<bool>("answer2check")
                        .HasColumnType("bit");

                    b.Property<bool>("answer3check")
                        .HasColumnType("bit");

                    b.Property<bool>("answer4check")
                        .HasColumnType("bit");

                    b.HasKey("SondageId");

                    b.ToTable("Sondages");
                });
#pragma warning restore 612, 618
        }
    }
}
